### ISSUE TITLE
pthread.h not found and vulkan library missing 

### ISSUE THREAD

**Issue by amenak** [cisc3620/1-open-window#3]
@rivlev I was able to run cmake and I get this output:

amena@DESKTOP-RPI7LFU /cygdrive/c/Users/amena/ SCHOOL/Spring 2017/CISC3620/labs/1-open- window-amenak/build
$ cmake -G "Visual Studio 14" ..
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- **Looking for pthread.h - not found**
-- Found Threads: TRUE
-- **Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR)**
-- Using Win32 for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/amena/SCHOOL/Spring 2017/CISC3620/Labs/1-open- window-amenak/Build

The instructions state:
"Follow the directions to clone this repository and generate a makefile. Compile and run. You should see a window with a gray background."
Nothing comes up when I run cmake. I've updated my graphics driver but that hasn't changed anything.

**Comment by rivlev** [comment]
Those warnings do not prevent it from working.

Cmake doesn't compile and run for you, it just creates the project.

Open the *project* (not just main.cpp) in visual studio and compile it there.

To run, find the executable, which should be in Build/Glitter/Debug and called Glitter. Double click on it from a file explorer to run.

See https://github.com/cisc3620/2-draw-triangle/issues/2
